server:
  port: 8030
eureka:
  client:
    service-url: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: Consumer_Clinet
spring:
  thymeleaf:
    prefix: classpath:/static/
    suffix: .html
