server:
  port: 8020
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orderingsystem?useUnicode=true&characterEncoding=utf-8&relaxAutoCommit=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: Meals_Menu_provider
    prefer-ip-address: true
mybatis:
  mapper-locations: classpach:mybatis/*.xml #接口映射文件路径
  type-aliases-package: com.junbaobao.pojo #映射实体路径